### ISSUE TITLE
I'm waiting patiently for BP_JVM_VERSION of 20 :-)

### ISSUE THREAD

**Issue by dxxvi** [paketo-buildpacks/bellsoft-liberica#390]

**Comment by juergenzimmermann** [comment]
See https://github.com/paketo-buildpacks/bellsoft-liberica/pull/386

**Comment by burl21** [comment]
> See https://github.com/paketo-buildpacks/bellsoft-liberica/pull/386

When is the release scheduled for ?

**Comment by juergenzimmermann** [comment]
Regarding commit https://github.com/paketo-buildpacks/bellsoft-liberica/commit/5aa5275c8c27d084ffcf49fa9d4724756aa0730f I asked @dmikusa who redirected to @pivotal-david-osullivan and mentioned that releases are published on Fridays. Therefore, I _hope_ that there will be a release after the easter holidays.
BTW, I'm using Gradle with Spring Boot and changed my `build.gradle.kts` to use _SapMachine_ 20 instead of _Bellsoft Liberica_: it works fine.

**Comment by dmikusa** [comment]
Bellsoft Liberica release cut just now. We're going to update the composite Java buildpack and release that shortly.
