### ISSUE TITLE
BPL_JVM_THREAD_COUNT not works

### ISSUE THREAD

**Issue by uqix** [paketo-buildpacks/bellsoft-liberica#68]
## What happened?

When building a spring boot app, `BPL_JVM_THREAD_COUNT` and `JAVA_TOOL_OPTIONS` are specified for `pack`, but running on k8s results in error:

```
Setting Active Processor Count to 2
unable to calculate memory configuration
fixed memory regions require 625098K which is greater than 600M available for allocation: -XX:MaxDirectMemorySize=10M, -XX:MaxMetaspaceSize=113098K, -XX:ReservedCodeCacheSize=240M, -Xss1M * 250 threads
```

It seems that the memory calculator(uses `-Xss1M * 250 threads`) does not know the options I passed to pack(100 * 256k).

## Build Configuration

```sh
         pack build $image_name \
           --builder $pack_builder \
           --volume `dirname $0`/paketo/dependency-mapping:/platform/bindings/dependency-mapping \
           --pull-policy if-not-present \
           --env BP_JVM_VERSION=$bp_jvm_version \
           --env BPL_JVM_THREAD_COUNT=100 \
           --env JAVA_TOOL_OPTIONS="-Xss256k" \
           --path target/*.jar
```

**Comment by uqix** [comment]
Passing these vars at runtime works

**Comment by JohannesRudolph** [comment]
I think this should be reopened, running into the same issue here. https://stackoverflow.com/a/66909132/125407 suggested overriding with the environment variable buildpack like `BPE_OVERRIDE_BPL_JVM_THREAD_COUNT` but that feels like a workaround.

**Comment by dmikusa-pivotal** [comment]
None of the answers in that SO post get it exactly right, which might be part of the issue.

It's important to understand that there are two different times where code runs: at build time and at runtime. 

1. You can set env variables at build time using Spring Boot in your Maven or Gradle config. You just give it a list of env variables to set. See here https://docs.spring.io/spring-boot/docs/2.5.1/maven-plugin/reference/htmlsingle/#build-image.customization. Those will only be set at build time though.

2. If you want env variables set at runtime, then it's not something Spring Boot or the buildpacks can control. This is because neither are involved when your app image is actually run. To pass env variables to your app image at runtime, you need to use the facilities of whatever is running your app image, like Docker or Kubernetes. For Docker, it's just `docker run -e foo=bar ...`. For Kubernetes, it's in the pod spec.

    Any env variable that is prefixed with `BPL_` means it only applies at run time (the `L` is for launch). FYI. Thus it would only make sense to set those when your app runs.

3. The environment variables buildpack is a mix of the two. If you set env variables using option #1 above but prefixed in a certain way, this buildpack will see them and turn them into env variables that are embedded into the image. This will have the effect of setting them at runtime, but it's not often what you want. For example, you certainly wouldn't want this if you're trying to set something sensitive like a password or secret key, because that would end up in your image and anyone seeing the image can see that value.

Where I'm going with all this is that you cannot set `BPL_JVM_THREAD_COUNT` with pack or Maven or Gradle and expect it to work because that is only being set in the runtime container. You must instead set it with `docker run -e BPL_JVM_THREAD_COUNT=100 ...` or in your Kubernetes YAML. It needs to be set at runtime to be effective. The same goes for `JAVA_TOOL_OPTIONS`. You can set them at build time, but they'll only apply to `java` processes that run at build time, like Maven or Gradle, and not your app at runtime. You would need to make sure that `JAVA_TOOL_OPTIONS` is set at runtime by Docker or Kubernetes (or whatever runs your containers) to have it apply to your actual application.

**Comment by JohannesRudolph** [comment]
Thanks a lot for your thorough reply. What I think many image authors are trying to achieve (well, certainly I am) is to ship a "default" setting for these variables with the built container image. Users should be able to override these env vars from their execution tools, but I want my container to work well out of the box in a low memory env. 

The documentation for the memory calculator creates the impression that these setting would do that trick, but apparently they don't. Which makes me wonder what the point of them is at all?

**Comment by dmikusa-pivotal** [comment]
If you want to set default values, you want to use the environment variables buildpack. See my post on your SO link.
